#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application="myElasticNonLinULSolidFoam"

runApplication blockMesh
runApplication setSet -batch batch.setSet
runApplication setsToZones -noFlipMap
\cp -f 0/org/materials 0/materials
runApplication setFields
runApplication $application
